### ISSUE TITLE
run 2006-10 summary files

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/ACS#101]
@Woliver01  - can you create these summar files for 2006-10? 
instructions: https://urbanorg.app.box.com/notes/52142895141

**Comment by Woliver01** [comment]
@lhendey I don't have the DCDATA folder in the C:\ drive where the Acs_xxxx_yy_ss_sum_all.sas template is. Where can I find it?

**Comment by lhendey** [comment]
@Woliver01 - template should be here: L:\Libraries\ACS\Prog\Templates

**Comment by lhendey** [comment]
@Woliver01 = sorry - you should have it on D:\DCData\Libraries\ACS\Prog\Templates\Acs_xxxx_yy_ss_sum_all.sas

**Comment by rpitingolo** [comment]
@lhendey the 2012-16 summary files don't have the units by bedroom size variables. Since you updated the macros already, is it correct that we just need to batch submit the 2012-16 programs so that the variables are available for use there?

**Comment by lhendey** [comment]
@rpitingolo = i think that yipeng's code overwrote mine. None of the variables and reorganizing i did are in https://github.com/NeighborhoodInfoDC/ACS/blob/master/Macros/ACS_summary_geo_source_tr_vars.sas - i seem to remember a conflict with master? can you please take a look?

**Comment by lhendey** [comment]
@rpitingolo - there are a lot of changes that got missed https://github.com/NeighborhoodInfoDC/ACS/compare/bugfix-%23103...master

**Comment by lhendey** [comment]
@rpitingolo - please hold off on resolving it. @ptatian is going to look up the best way to resolve it. likely

**Comment by rpitingolo** [comment]
@lhendey OK. Will hold off until further notice.

**Comment by ptatian** [comment]
Created a new issue #110 to address this problem.
