### ISSUE TITLE
Bug-Fix Proc Compare for Council District file

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/ACS#103]
@ptatian - tried to adjust acs summary geo
to subset weight file - issue is on council district file. no errors in log and looks like base and comparison files have the same N but - data is not adding up. thoughts? using
D:\DCDATA\Libraries\ACS\Prog\SF_2012_16\ACS_2012_16_md_sum_all.sas to test on enhancement-#88

**Comment by ptatian** [comment]
@lhendey I think led you in the wrong direction (sorry). It's the _input data set_ that should be filtered to only the areas needed in the output file, not the weight file. The current input data (ACS_2012_16_MD_SUM_TR_TR10) has all MD tracts, but we only want a few counties in the regional files. In the Proc Compare output,

```
__________________________________________________________
           ||  Total population, 2012-16
           ||       Base    Compare
       Obs ||  TotPop_20  TotPop_20      Diff.     % Diff
           ||      12_16      12_16
 ________  ||  _________  _________  _________  _________
           ||
        1  ||    5959902    2412413   -3547489   -59.5226
__________________________________________________________
```

The first number is the pop for the entire state of MD (i.e., total from the input data set). The second is the pop for the counties in the region (i.e., total from the output data set). What it's checking is that _totals from input = totals from output_, which, of course, they don't. 

Again, fixing this won't affect the output data set at all, but it will eliminate the extraneous output.

Sorry for the confusion.

**Comment by lhendey** [comment]
@ptatian - just double checking...
so i should subset the &source_ds_work file going into the %transform_geo_data macro? 

 %Transform_geo_data(
		      dat_ds_name=&source_ds_work,
		      dat_org_geo=&source_geo_var,
		      dat_count_vars=&count_vars,
...

**Comment by ptatian** [comment]
@lhendey Yes, the _dat_ds_name=_ data set should be subsetted to include only those areas that will go into the output data.

**Comment by lhendey** [comment]
@ptatian [https://github.com/NeighborhoodInfoDC/ACS/commit/e8088f217d6f2e6c8bfdb6722588839f337289e9](url) switched subsetting and will commit this change under issue #101
