### ISSUE TITLE
Housing unit count vars missing from ACS summary files for MD, VA, WV

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/ACS#112]
Variables _numhsgunits*_ and _mnumhsgunits*_ are in the DC summary files but not in the files for other states (Acs.Acs_2012_16_md_sum_regcnt_regcnt, Acs.Acs_2012_16_md_sum_tr_regcd, etc.)

**Comment by ptatian** [comment]
@rpitingolo @lhendey @maggiesu0725 Realizing this was probably a result of adding the housing unit count vars to the file for the large unit study. Perhaps the VA, MD, and WV files just didn't get rerun?

**Comment by lhendey** [comment]
@ptatian that's what it looks like on L. the log and list files date back to 6/8 so wouldn't account for the fix @rpitingolo did last week.

**Comment by ptatian** [comment]
Thanks @lhendey. So can someone just resubmit those? @rpitingolo?

**Comment by lhendey** [comment]
@ptatian i just resubmitted VA, MD, and WV. @rpitingolo is out of the office today.

**Comment by ptatian** [comment]
Thanks, @lhendey. I'm updating the metadata now.

**Comment by rpitingolo** [comment]
@lhendey @ptatian yes, sorry. This should be as simple as batch submitting the other states.
