### ISSUE TITLE
separate out no cash rent

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/ACS#122]
@rpitingolo - is there anyway you can edit (tomorrow) https://github.com/NeighborhoodInfoDC/ACS/blob/master/Macros/ACS_summary_geo_source_tr_vars.sas 

to separate out no cash rent from the lower category? 
numRtOHU0Bunder500_ 
numRtOHU1Bunder500_
numRtOHU2Bunder500_
numRtOHU3Bunder500_ (and their MOEs).  Then i'd want to update the rent_levels sheet on 1A.

**Comment by rpitingolo** [comment]
@lhendey yes I can do this today.
