### ISSUE TITLE
Fix married family variable from table B11001

### ISSUE THREAD

**Issue by maggiesu0725** [NeighborhoodInfoDC/ACS#131]
FamMarriedCouple_&_years.= B11001e2;
should be  B11001e3;

@ptatian

**Comment by ptatian** [comment]
Thanks for tracking this down @maggiesu0725. Do you feel comfortable making this fix? cc: @rpitingolo @lhendey

**Comment by maggiesu0725** [comment]
yes I can fix this, the only program that need updating is ACS_summary_geo_source_tr_vars right? @ptatian @rpitingolo

**Comment by ptatian** [comment]
@maggiesu0725 You should also update the _revisions=_ messages in the programs for the data sets we are going to rerun. That will document in the metadata what the changes were to the data sets. @rpitingolo
