### ISSUE TITLE
Add indicators for digital access to 2013-17 summary files

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/ACS#138]
- [x]  edit ACS_summary_geo_source_tr_vars.sas macro to create numerators and denominators for indicators. (label indicators). you'll need to use %if %then %do statements to make sure these indicators will only appear on 2013-17 and later files and not result in unitialized vars on earlier years. see for example where NumRtOHU0Bnocash_&_years. gets created. 

- [x] edit Acs_summary_geo.sas to add new indicators. create new %let statement for moes that appear only 2017 and after and edit code to capture this. 

- [x] request review and finalize.

**Comment by lhendey** [comment]
@maggiesu0725  can we close this issue?

**Comment by maggiesu0725** [comment]
Is it OK to close this issue? I batch submited on 12. 16. L:\Libraries\ACS\Prog\SF_2013_17\Acs_sf_2013_17_dc.log

**Comment by lhendey** [comment]
@maggiesu0725 yes
