### ISSUE TITLE
add more internet-computer tables to acs_sf.sas

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/ACS#149]
Add table B28001, B28002, B28003, B28005, B28008, B28011

**Comment by lhendey** [comment]
@maggiesu0725 - did you batch submit these? can you do so and close the issue?

**Comment by maggiesu0725** [comment]
batch submitted. 
L:\Libraries\ACS\Prog\SF_2013_17\Acs_sf_2013_17_dc.log
L:\Libraries\ACS\Prog\SF_2013_17\Acs_sf_2013_17_md.log
L:\Libraries\ACS\Prog\SF_2013_17\Acs_sf_2013_17_va.log
L:\Libraries\ACS\Prog\SF_2013_17\Acs_sf_2013_17_wv.log
