### ISSUE TITLE
add total households from table B28002

### ISSUE THREAD

**Issue by maggiesu0725** [NeighborhoodInfoDC/ACS#155]
The rows in table 28002 are not mutually exclusive so we can't add up the rows to get the total. Pull in total row.

**Comment by maggiesu0725** [comment]
L:\Libraries\ACS\Prog\SF_2013_17\ACS_2013_17_dc_sum_all.log
L:\Libraries\ACS\Prog\SF_2013_17\ACS_2013_17_md_sum_all.log
L:\Libraries\ACS\Prog\SF_2013_17\ACS_2013_17_va_sum_all.log
L:\Libraries\ACS\Prog\SF_2013_17\ACS_2013_17_wv_sum_all.log

**Comment by lhendey** [comment]
@maggiesu0725 you need to remember to sync before batch submitting on L. your changes on this issue were not reflected in those programs. I'm batch submitting now.

**Comment by lhendey** [comment]
Resubmittd. 
L:\Libraries\ACS\Prog\SF_2013_17\ACS_2013_17_dc_sum_all.log
L:\Libraries\ACS\Prog\SF_2013_17\ACS_2013_17_md_sum_all.log
L:\Libraries\ACS\Prog\SF_2013_17\ACS_2013_17_va_sum_all.log
L:\Libraries\ACS\Prog\SF_2013_17\ACS_2013_17_wv_sum_all.log
