### ISSUE TITLE
Pull needed ACS tables for racial equity project

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/ACS#16]
Update Acs_sf_2010_14_dc.sas  to pull new tables as discussed.

**Comment by sdiby** [comment]
At least two sets of tables (**B01001/A-F and B17001/A-I**) that exist in the remote raw data are being erased from the local raw data folder after running the program (observe **edc_002, mdc_002, edc_0047, and mdc_0047** before and after running the program).

In the acs_sf macro, please review where and how these data are being excluded.
