### ISSUE TITLE
Add summary indicators for Reg AI

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/ACS#175]
- [x] edit ACS_summary_geo_source_tr_vars.sas macro to create numerators and denominators for indicators. (and label all the indicators).
- [x] edit Acs_summary_geo.sas to add new indicators.
- [x] request review and finalize.

**Comment by ahariharan7** [comment]
- [ ] List all variables that are being flagged as uninitialized
- [ ] Initialize uninitialized variables in acs_sf macro in new  branch
- [ ] run that
