### ISSUE TITLE
Process ACS 2017-21 5 year summary tabulations

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/ACS#196]
Follow steps on [this box note](https://urbanorg.app.box.com/notes/51315236817)

**Comment by RAGarMir** [comment]
\\SAS1\dcdata\Libraries\ACS\Prog\SF_2017_21\Acs_sf_2017_21_DC.log
\\SAS1\dcdata\Libraries\ACS\Prog\SF_2017_21\Acs_sf_2017_21_MD.log
\\SAS1\dcdata\Libraries\ACS\Prog\SF_2017_21\Acs_sf_2017_21_VA.log
\\SAS1\dcdata\Libraries\ACS\Prog\SF_2017_21\Acs_sf_2017_21_WV.log
