### ISSUE TITLE
Run Geography Summary Files for ACS 2017-21

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/ACS#197]
Follow instructions on this note: https://urbanorg.app.box.com/notes/52142895141

**Comment by RAGarMir** [comment]
\\SAS1\dcdata\Libraries\ACS\Prog\SF_2017_21\ACS_2017_21_DC_sum_all
\\SAS1\dcdata\Libraries\ACS\Prog\SF_2017_21\ACS_2017_21_MD_sum_all
\\SAS1\dcdata\Libraries\ACS\Prog\SF_2017_21\ACS_2017_21_VA_sum_all
\\SAS1\dcdata\Libraries\ACS\Prog\SF_2017_21\ACS_2017_21_WV_sum_all
