### ISSUE TITLE
Process ACS 2018-22 5 year summary tabulations

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/ACS#198]
Follow steps on [this box note](https://urbanorg.app.box.com/notes/51315236817)

**Comment by ptatian** [comment]
@RAGarMir @lhendey Realizing that I should have dealt with [this issue](https://github.com/NeighborhoodInfoDC/ACS/issues/106) as part of the new process I created. You can keep working on this, but please hold off on final batch submits until I get that fixed!

**Comment by lhendey** [comment]
@RAGarMir new instructions https://urbanorg.app.box.com/notes/1412616810252?s=yrtumjob9lfuarcwqorpc9oowg4p01kg

**Comment by RAGarMir** [comment]
[like]  Garcia, Rodrigo reacted to your message:
________________________________

**Comment by ptatian** [comment]
@RAGarMir @lhendey I've fixed issue #106. You can proceed without any problems.

**Comment by ptatian** [comment]
Please note that the new county file will have a suffix of _cnty and the county variable in this file is now ucounty.

**Comment by ptatian** [comment]
Hi @RAGarMir. I should have mentioned that if you have not yet created a new GitHub branch for this update, then you will be fine going forward. Just make sure you fetch and pull all the changes from the master branch to your local ACS repo before creating your new branch.

If you already created a new update branch before the end of yesterday, when I pushed my code updates, then you will need to pull those changes into your branch before proceeding. This can be done in the GitHub app using the "Branch > Update from master" menu command. 

If any of that is confusing, just let Leah or me know and we will walk you through it. Thanks!

**Comment by ptatian** [comment]
@RAGarMir How are things going with the ACS data? Have you tried any full batch submits yet?

**Comment by RAGarMir** [comment]
> @RAGarMir How are things going with the ACS data? Have you tried any full batch submits yet?
Hello @ptatian. Sorry for the late response and message. Currently running the ACS full batch submits. No major issues, I should be done with the final batch submits this afternoon.
