### ISSUE TITLE
Add summary file data for 2009-13

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/ACS#2]
https://urbanorg.app.box.com/notes/51315236817

**Comment by chedman** [comment]
@ptatian can you check to see if I am a collaborator on this? I am having issue changing the status. Thanks!

**Comment by ptatian** [comment]
Yep, sorry. I forgot to add you to the Core team, which gives you access to all of the repositories. Try it now. -P

**Comment by chedman** [comment]
Looks like it worked. Thanks!

Carl

**Comment by ptatian** [comment]
Yes, you are now the issue owner and its status has been changed to in progress. https://waffle.io/NeighborhoodInfoDC/ACS

**Comment by chedman** [comment]
@ptatian it looks like there were no errors when I tested the program so I think it is good for review.

**Comment by ptatian** [comment]
@chedman Great! But, you have to publish your branch so that I can review the code.

**Comment by chedman** [comment]
@ptatian hmm.. the branch should be published under the name "update-#2". Is it not showing up?

**Comment by ptatian** [comment]
@chedman Did you make a pull request? Try sync'ing it again.

**Comment by ptatian** [comment]
@chedman I finished the review and everything looks good! I merged the pull request into master and deleted the update branch. You can now proceed with step 8 in the instructions. Thanks!

**Comment by chedman** [comment]
@ptatian great - thanks!
