### ISSUE TITLE
Revised ACS 2018-22 5 year Summary Tabulations to include final batch submit preparations

### ISSUE THREAD

**Issue by RAGarMir** [NeighborhoodInfoDC/ACS#210]

**Comment by lhendey** [comment]
"\sas1\dcdata\Libraries\ACS\Prog\SF_2018_22\ACS_2018_22_WV_sum_all.log"
"\sas1\dcdata\Libraries\ACS\Prog\SF_2018_22\ACS_2018_22_DC_sum_all.log"
"\sas1\dcdata\Libraries\ACS\Prog\SF_2018_22\ACS_2018_22_MD_sum_all.log"
"\sas1\dcdata\Libraries\ACS\Prog\SF_2018_22\ACS_2018_22_VA_sum_all.log"
