### ISSUE TITLE
Replace MOEs with -555555555 as 0

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/ACS#214]
https://www.census.gov/data/developers/data-sets/acs-1year/data-notes.html 

Possible values
-555555555

-555555555.0

-555555555.00

Edit compile_acs_new.sas macro in the section:
 ** Recode margin of error = -1 to .N (not available) **;
    **** CENSUS HAS NEW CODES FOR MOE VALUES ;
    **** CURRENTLY THOSE CODES ARE LEFT AS IS AND NOT RECODED TO SAS MISSING VALUES ;
    
    array moe{*} &table_m_list;
    
    do i = 1 to dim( moe );
    
      if moe{i} = -1 then moe{i} = .n;
      
    end;

**Comment by ptatian** [comment]
Thanks @lhendey. It would not be hard to program this, but it will add to the runtime on the downloading programs. Although it might be easier to build it into the %Get_acs_detailed_table_api() macro because that macro has a list of the MOE variables as a local macro var. Users could specify recodes they want.

In the older data/code, we recoded MOEs with values -1 as missing.

**Comment by ptatian** [comment]
Census may have had different approaches in the past, hence now multiple codes rather than just -1. I think I would make them all some type of missing value.

**Comment by ptatian** [comment]
Alternatively, we could add it to the programs that create the summary statistics, so that we don't have to redownload all the ACS data.

**Comment by lhendey** [comment]
@ptatian I just discovered more of these codes popping up -both on estimates and MOEs - (i was getting negative avg hh income...)  B19025De1 B19025Dm1 B19025Ee1 B19025Em1.  -666666666 on the estimate and -222222222 on the MOE. it feels like we definitely need to update the Summary stats at least.

**Comment by lhendey** [comment]
"\sas1\dcdata\Libraries\ACS\Prog\SF_2018_22\ACS_2018_22_WV_sum_all.log"
"\sas1\dcdata\Libraries\ACS\Prog\SF_2018_22\ACS_2018_22_DC_sum_all.log"
"\sas1\dcdata\Libraries\ACS\Prog\SF_2018_22\ACS_2018_22_MD_sum_all.log"
"\sas1\dcdata\Libraries\ACS\Prog\SF_2018_22\ACS_2018_22_VA_sum_all.log"
