### ISSUE TITLE
Create ACS geo summary files for 2011-15

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/ACS#31]
https://urbanorg.app.box.com/notes/52142895141

**Comment by chedman** [comment]
@ptatian @rpitingolo OK, that sounds good. I'll get started working through the instructions now.

**Comment by chedman** [comment]
@ptatian Just double checking - you get a notification when I create a pull request, right? Or should I comment on this thread when a program needs review? Thanks

**Comment by ptatian** [comment]
No, I don't automatically get notified when you do a pull request. You should mention @NeighborhoodInfoDC/review in the pull comment to request a review. 
I will review.

**Comment by chedman** [comment]
@ptatian Oh, sorry. I'll make sure to include that next time.

**Comment by ptatian** [comment]
Carl, something seems off as you didn't fill in the macro parameters in the program template. Did you sync up all your commits?
