### ISSUE TITLE
Prepare regional ACS data for Greater DC website

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/ACS#73]
- [ ] Add West Virginia to state summary files
- [ ] Add place-level summary files

**Comment by ptatian** [comment]
@rpitingolo The complete county format for the MSA is called $cnty15f.

**Comment by lhendey** [comment]
@rpitingolo - is this one ready to be merged?

**Comment by ptatian** [comment]
@rpitingolo Merge? Close?

**Comment by ptatian** [comment]
This issue is no longer needed.
