### ISSUE TITLE
Uninitialized variables in summary data sets

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/ACS#74]
@rpitingolo In doing an update of the ACS data, we found some uninitialized variable problems. You can review the LOGs for the latest updates. In particular, the PopEmployedWorkers, PopEmployedWorkIn..., etc. variables have all missing values in the MD, VA, and WV summary data sets.

**Comment by ptatian** [comment]
needs #93

**Comment by lhendey** [comment]
@ptatian - this doesn't seem to an issue on 2012-18 data?

**Comment by ptatian** [comment]
Maybe it got fixed with the changes we've made? If it's no longer a problem we can close the issue.

**Comment by lhendey** [comment]
@ptatian - agreed-  i think after we finish moving the bg vars to tract source then we should rerun the back years so we have a consistent set of files, that should probably take care of this one.
