### ISSUE TITLE
Update 2012-16 ACS

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/ACS#75]
@ptatian creating this issue in advance of the data release. @chedman has time the week of Dec 11th to go through the update process.

**Comment by chedman** [comment]
@rpitingolo The program is ready for review.

**Comment by chedman** [comment]
@rpitingolo just added the va, md, and wv programs

**Comment by rpitingolo** [comment]
@chedman thanks. I'm reviewing.

**Comment by rpitingolo** [comment]
@chedman can you make sure you've committed these and synced? I only see a commit from 4 hours ago.

**Comment by chedman** [comment]
@rpitingolo oh sorry - it should be synced now.
