### ISSUE TITLE
Shorten regional council district format names

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/ACS#78]

**Comment by rpitingolo** [comment]
@lhendey should I try to shorten all of the names to less than 32 characters or just the ones where the district number comes at the end? For example "Prince William, Woodbridge District" is 35 characters but since the name comes before "District" it will still process through the proc transpose without erroring.

**Comment by rpitingolo** [comment]
Realized I opened this issue in the wrong repo. Moving now.

**Comment by lhendey** [comment]
I think leaving it is fine in that case since it won’t affect the processing.
