### ISSUE TITLE
Add tables for Large Units study to Acs_sf.sas

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/ACS#87]
D:\DCData\Libraries\ACS\Macros\Acs_sf.sas See "Adding Tabulations " section of instructions https://urbanorg.app.box.com/notes/51315236817 
B25031, B25041, B25042, B25068

**Comment by ptatian** [comment]
@Woliver01 Please also add this table for the State of Immigrants study:
**B05006**

Thank you.

**Comment by ptatian** [comment]
@Woliver01 Sorry, please add the following tables as well:
**B27001, B25095, B25074, B14001**

Thank you.
